version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/ssdae/api
    ports:
      - "3000:3000"
    depends_on:
      - db